language: python
python:
  - 2.6
  - 2.7
install:
  - python bootstrap.py
  - bin/buildout -c buildout.d/travis.cfg -q
script:
  - ./pre-commit-check.sh
 
notifications:
  irc:
    - "irc.freenode.org#niteoweb"
  email:
    - maintenance@niteoweb.com
